name: PR Approval

on:
    pull_request_target:
        types: [opened, synchronize, reopened, ready_for_review, review_requested, review_request_removed, edited]

jobs:
    require-approval:
        runs-on: ubuntu-latest
        steps:
            - name: Check for maintainer approval
              uses: hmarr/auto-approve-action@v3
              if: github.event.pull_request.user.login != 'github-actions[bot]'
